### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by tomholford** [BlakeWilliams/b-r-o-w-s-e#1]
Had trouble building this on Big Sur, sharing this just in case it's useful for troubleshooting:

https://github.com/johnste/finicky/releases/tag/v3.1.3

**Comment by BlakeWilliams** [comment]
Thanks for the report!

I'll take a peek and see if I can get this building again.

**Comment by BlakeWilliams** [comment]
Okay, I just pushed up a change that I think should make it build. Feel free to re-open if that doesn't work.
